[versions]
javassist = "3.29.2-GA"
gradle-api = "8.8.0-alpha08"

[libraries]
javassist = { module = "org.javassist:javassist", version.ref = "javassist" }
gradle-api = { module = "com.android.tools.build:gradle-api", version.ref = "gradle-api" }