[versions]
guava = "33.0.0-jre"
junit-jupiter = "5.10.2"
javassist = "3.29.2-GA"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
javassist = { module = "org.javassist:javassist", version.ref = "javassist" }